include:
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.default.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.rules.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.scripts.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.variables.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.workflow.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/build.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/test.windows.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/quality.yml

default:
  image: registry.gitlab.com/reductech/containers/dotnet/sdk:3.1
  tags:
    - rt-windows

stages:
  - build
  - test
  - quality
  - package

variables:
  PACKAGE_NAME_EXE: Reductech.EDR

.exe_artifacts_default:
  artifacts:
    name: "$PACKAGE_NAME_EXE-$PROJECT_VERSION"
    paths:
      - CHANGELOG.md
      - EDR.exe
      - EDR.pdb
      - LICENSE
      - README.md

package exe dev:
  stage: package
  extends:
    - .rules_manual
    - .exe_artifacts_default
  needs:
    - build dev
    - test dev
    - version check dev
  script:
    - dotnet publish --no-build --configuration $CONFIG_DEV --version-suffix $VERSION_SUFFIX
      -p:PublishSingleFile=true --output ./
  artifacts:
    expire_in: 3 months

package exe release:
  stage: package
  extends:
    - .rules_release
    - .exe_artifacts_default
  needs:
    - build release
    - test release
    - version check release
  script:
    - dotnet publish --no-build --configuration $CONFIG_RELEASE
      -p:PublishSingleFile=true --output ./
  artifacts:
    expire_in: never

code_quality:
  tags:
    - rt-dind
