include:
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.default.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.rules.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.scripts.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.variables.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/default.workflow.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/build.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/test.windows.yml
  - project: reductech/templates/cicd/dotnet
    file: .gitlab/ci/quality.yml

default:
  image: mcr.microsoft.com/dotnet/sdk:5.0-windowsservercore-ltsc2019
  tags:
    - rt-windows

stages:
  - build
  - test
  - quality
  - package
  - package-test
  - sign

variables:
  PACKAGE_NAME_EXE: Reductech.EDR

.exe_artifacts_default:
  artifacts:
    name: '$PACKAGE_NAME_EXE-$PROJECT_VERSION'
    paths:
      - lib/
      - CHANGELOG.md
      - EDR.exe
      - LICENSE
      - README.md

package exe dev:
  stage: package
  extends:
    - .rules_dev_manual
    - .exe_artifacts_default
  needs:
    - build dev
    - test dev
    - version check dev
  script:
    - dotnet publish --no-build --configuration $CONFIG_DEV --output ./lib
      --version-suffix $VERSION_SUFFIX
    - ./single-fileish.ps1
  artifacts:
    expire_in: 3 months

package exe release:
  stage: package
  extends:
    - .rules_release
    - .exe_artifacts_default
  needs:
    - build release
    - test release
    - version check release
  script:
    - dotnet publish --no-build --configuration $CONFIG_RELEASE --output ./lib
    - ./single-fileish.ps1
  artifacts:
    expire_in: 2 hours

# Test the package
test package exe dev:
  stage: package-test
  tags:
    - nuix
  cache: {}
  extends:
    - .rules_dev_manual
  needs:
    - package exe dev
  script:
    - .\EDR.exe -p .\Examples\core-sequence.scl
    - .\EDR.exe -p .\Examples\nuix-sequence.scl
    - .\EDR.exe -p .\Examples\pwsh-sequence.scl

test package exe release:
  extends:
    - test package exe dev
    - .rules_release
  needs:
    - package exe release

sign exe release:
  stage: sign
  image: registry.gitlab.com/reductech/containers/codesigning
  cache: {}
  extends:
    - .rules_release
    - .exe_artifacts_default
  needs:
    - version check release
    - package exe release
    - test package exe release
  variables:
    TIMESTAMP_SERVER: http://timestamp.sectigo.com
    ALGO_FILE_DIGEST: SHA256
    ALGO_TIME_DIGEST: SHA256
  script:
    - signtool.exe sign /f $RT_CERT_PATH /p $RT_CERT_PASS /fd $ALGO_FILE_DIGEST
      /tr $TIMESTAMP_SERVER /td $ALGO_TIME_DIGEST .\EDR.exe
    - signtool.exe sign /f $RT_CERT_PATH /p $RT_CERT_PASS /fd $ALGO_FILE_DIGEST
      /tr $TIMESTAMP_SERVER /td $ALGO_TIME_DIGEST .\lib\EDR.exe
  artifacts:
    expire_in: never

code_quality:
  tags:
    - rt-dind

mutation testing:
  rules:
    - when: never

code coverage dev:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  tags:
    - rt-linux

code coverage release:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  tags:
    - rt-linux
