variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - test
    - release

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - EDR/bin/

test:
    stage: test
    script: 
        - "dotnet test --filter TestCategory!=\"Integration\""
        
release:
    stage: release
    rules:
    - if: '$CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/i'
      when: on_success
    script:
        - "dotnet publish --runtime win-x64 --configuration release"
    artifacts:
      paths:
        - EDR/bin/Release/netcoreapp3.1/win-x64