include:
  - project: reductech/templates/cicd/dotnet
    file: .gitlab-ci.windows.yml

stages:
  - build
  - test
  - quality
  - package_exe

variables:
  PACKAGE_NAME_EXE: Reductech.EDR

.exe_artifacts_default:
  artifacts:
    name: "$PACKAGE_NAME_EXE-$PROJECT_VERSION"
    paths:
      - CHANGELOG.md
      - EDR.exe
      - EDR.pdb
      - LICENSE
      - README.md

package exe dev:
  stage: package_exe
  extends:
    - .rules_dev
    - .exe_artifacts_default
  needs:
    - build dev
    - test dev
    - version check dev
  script:
    - dotnet publish --no-build --configuration $CONFIG_DEV
      -p:PublishSingleFile=true --output ./
  artifacts:
    expire_in: 3 months

package exe release:
  extends:
    - package exe dev
    - .rules_release
    - .exe_artifacts_default
  needs:
    - build release
    - test release
    - version check release
  artifacts:
    expire_in: never
